# -*- coding: utf-8 -*-
"""SpotiFyColab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n5_EDck2kKCeEwrdXZrZ868L8wRf7eZF
"""

import pandas as pd
import numpy as np

d1960 = pd.read_csv("60.csv", header=None, sep=";")
display(d1960.head(10000))

d1970 = pd.read_csv("70.csv", header=None, sep=";")
display(d1970.head(10000))

d1980 = pd.read_csv("80.csv", header=None, sep=";")
display(d1980.head(10000))

d1990 = pd.read_csv("90.csv", header=None, sep=";")
display(d1990.head(10000))

d2000 = pd.read_csv("2000.csv", header=None, sep=";")
display(d2000.head(10000))

d2010 = pd.read_csv("2010.csv", header=None, sep=";")
display(d2010.head(10000))

df_decadas=pd.concat([d1960,d1970,d1980,d1990,d2000,d2010])
display(df_decadas.head(60000))

df_decadas.to_csv("saida_6decadas_colab.csv", index=False, sep=";", encoding="utf-8-sig")